
baseURL: https://scottaubrey.info/
languageCode: en-GB
timeZone: Europe/London

theme: "sustain"
title: "Scott Aubrey"

params:
  avatar: img/headshot.jpg
  author: Scott Aubrey
  description: My personal website
  social:
    Github: scottaubrey
    Email: "scott@aubrey.org.uk"
    Twitter: scottaubrey
    RSS: /blog/index.xml

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    style: solarized-dark256
    tabWidth: 4

menu:
  main:
  - name: About
    identifier: about
    weight: 100
    url: /about/
  - name: blog
    weight: 200
    identifier: blog
    url: /blog/
